### ISSUE TITLE
tag / attach binary

### ISSUE THREAD

**Issue by andrewhowdencom** [zwopir/osquery_exporter#2]
Hola! This project looks cool; I'm building a small set of ansible script so I can play with it on a set of Raspberry pis running displays. 

Any chance you can tag a "1.0" and upload the binaries for various architectures to the releases page? 

<3 Cheers!

**Comment by zwopir** [comment]
Hi Andrew,

sure - just need to find some time for doing it. Can you make sure osquery is available or at least compiles on ARM? otherwise it wouldn't make sense to offer an osquery_exporter for ARM

**Comment by andrewhowdencom** [comment]
It compiles -- 

```
(on Linux AMD64 machine)

env GOOS=linux GOARCH=arm go build github.com/zwopir/osquery_exporter
```

Execs also on a rpi in our office. I haven't tested it extensively on arm first, but it passes some sanity checks. 

```
$ go version
go version go1.7.4 linux/amd64
```

**Comment by zwopir** [comment]
I was talking about the osquery (https://osquery.io) binary, especially osqueryi. Its a requirement of the osquery_exporter. As far as I can see, its not available on ARM, but I might be wrong. See
https://github.com/facebook/osquery/issues/1424

**Comment by andrewhowdencom** [comment]
Oh crap right. I'll try it and get back to you in a bit.

**Comment by zwopir** [comment]
Hi @andrewhowdencom ,

have you found out if there's a ARM version os osquery? if not I would close this issue.

**Comment by andrewhowdencom** [comment]
I'll check to see if it compiles now. If you don't hear back from me in 30 minutes, you can close the issue.

Edit: It's still building. Will check back in 15. It's on pi3, they're reasonably underpowered!

**Comment by andrewhowdencom** [comment]
It's dead jim! I'm not going to debug OSQuery complation issues now. (: I appreciate your patience; thanks!

**Comment by zwopir** [comment]
you're welcome. Feel free to reopen the issue if you manage to find or compile a working osquery binary for the pi.
